Change order

diff --git a/.github/workflows/other-branch.yml b/.github/workflows/other-branch.yml
--- a/.github/workflows/other-branch.yml
+++ b/.github/workflows/other-branch.yml
@@ -8,6 +8,15 @@ on:
 jobs:
 
 
+  error:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Imprimir mensaje de error
+        run: |
+          echo "Este jobs genero un error"
+          exit 1
+  
   build:
     runs-on: ubuntu-latest
 
@@ -22,13 +31,6 @@ jobs:
       - name: Run test
         run: echo "Run Test"
 
-  error:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Imprimir mensaje de error
-        run: |
-          echo "Este jobs genero un error"
-          exit 1
+  
 
 
