error message

diff --git a/.github/workflows/other-branch.yml b/.github/workflows/other-branch.yml
--- a/.github/workflows/other-branch.yml
+++ b/.github/workflows/other-branch.yml
@@ -22,13 +22,13 @@ jobs:
       - name: Run test
         run: echo "Run Test"
 
-#  error:
-#    runs-on: ubuntu-latest
+  error:
+    runs-on: ubuntu-latest
 
-#    steps:
-#      - name: Imprimir mensaje de error
-#        run: |
-#          echo "Este jobs genero un error"
-#          exit 1
+    steps:
+      - name: Imprimir mensaje de error
+        run: |
+          echo "Este jobs genero un error"
+          exit 1
 
 
